apiVersion: apps/v1
kind: Deployment
metadata:
   name: sync
   namespace: agnost
   labels:
      app: sync
spec:
   replicas: 1
   selector:
      matchLabels:
         app: sync
   template:
      metadata:
         labels:
            app: sync
      spec:
         containers:
            - name: sync
              image: agnost-gitops/sync
              # We will be using the minikube docker daemon, since the actual docker daemon on local machine are different
              # Prevent minikube docker daemon to pull images from central docker hub set imagePullPolicy to Never, so that
              # it uses the image put in minikube's docker environment, see dev.sh script how we change the docker context to minikube
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              env:
                 - name: CACHE_HOSTNAME
                   valueFrom:
                      secretKeyRef:
                         name: redis
                         key: hostname 
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis
                         key: password
                 - name: NAMESPACE
                   value: agnost