apiVersion: v1
data:
  config.json: |-
    {
      "storage": {
        "rootDirectory":"/data",
        "commit": true,
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "zot" },
      "log": { "level": "debug" },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.json":"{\n  \"storage\": {\n    \"rootDirectory\":\"/tmp/zot\",\n    \"commit\": true,\n    \"dedupe\": true,\n    \"gc\": true,\n    \"gcDelay\": \"1h\",\n    \"gcInterval\": \"24h\"\n  },\n  \"http\": {\n    \"address\": \"0.0.0.0\",\n    \"port\": \"5000\",\n    \"realm\": \"zot\" },\n  \"log\": { \"level\": \"debug\" },\n  \"extensions\": {\n    \"search\": {\n      \"enable\": true\n    },\n    \"ui\": {\n      \"enable\": true\n    }\n  }\n}"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"agnost-gitops","meta.helm.sh/release-namespace":"agnost"},"creationTimestamp":"2024-07-26T07:28:14Z","labels":{"app.kubernetes.io/managed-by":"Helm"},"name":"zot","namespace":"agnost","resourceVersion":"43530","uid":"c889c391-817d-4cca-ac40-38bf9b337abe"}}
    meta.helm.sh/release-name: agnost-gitops
    meta.helm.sh/release-namespace: agnost
  creationTimestamp: "2024-07-26T07:28:14Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: zot
  namespace: agnost
  resourceVersion: "346259"
  uid: c889c391-817d-4cca-ac40-38bf9b337abe
