apiVersion: v1
kind: Secret
metadata:
  name: {{iid}}
  namespace: {{namespace}}
type: Opaque
stringData:
  username: {{secrets.username}}
  password: {{secrets.password}}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  serviceName: {{iid}}
  replicas: 1
  updateStrategy:
    type: {{statefulSetConfig.strategy}}
    rollingUpdate:
      maxUnavailable: {{statefulSetConfig.rollingUpdate.maxUnavailable}}
      partition: {{statefulSetConfig.rollingUpdate.partition}}
  revisionHistoryLimit: {{statefulSetConfig.revisionHistoryLimit}}
  podManagementPolicy: {{statefulSetConfig.podManagementPolicy}}
  persistentVolumeClaimRetentionPolicy: 
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: {{iid}}
  template:
    metadata:
      labels:
        app: {{iid}}
    spec:
      containers:
      - name: postgres
        image: {{registry.imageUrl}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: {{podConfig.memoryRequest}}{{podConfig.memoryRequestType}}
            cpu: {{podConfig.cpuRequest}}{{podConfig.cpuRequestType}}
          limits:
            memory: {{podConfig.memoryLimit}}{{podConfig.memoryLimitType}}
            cpu: {{podConfig.cpuLimit}}{{podConfig.cpuLimitType}}
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{iid}}
              key: username
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{iid}}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{iid}}
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/dstore
        livenessProbe:
          exec:
            command:
            - pg_isready
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 6
        readinessProbe:
          exec:
            command:
            - pg_isready
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 6
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/dstore
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{storageConfig.size}}{{storageConfig.sizeType}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}-headless
  namespace: {{namespace}}
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
  selector:
    app: {{iid}}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{iid}}
  namespace: {{namespace}}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: minio
  selector:
    app: {{iid}}